CREATE TABLE QUIZ(
    QID INTEGER PRIMARY KEY AUTOINCREMENT,
    QUESTION VARCHAR(300),
    OPTA VARCHAR(20),
    OPTB VARCHAR(20),
    OPTC VARCHAR(20),
    OPTD VARCHAR(20),
    CORRECT VARCHAR(20)
);


CREATE TABLE SCORES(
    PLR_NAME VARCHAR(20),
    PLR_SCORE INTEGER
);
